; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
extra_scripts = post:rename_bin.py

[env:adafruit_feather_m4]
extends=env
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
board_build.f_cpu = 180000000L
build_unflags = -Os
monitor_speed = 115200
upload_protocol = sam-ba
monitor_filters = time
build_flags =
    -DADAFRUIT_FEATHER_M4_EXPRESS
    -DUSE_TINYUSB
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -O3
    -flto
    -fno-exceptions
    -ffast-math
    -funroll-loops
    -DNDEBUG
    -fdata-sections
    -ffunction-sections
    -Wl,--gc-sections
    -fmerge-constants
    -funsigned-char
    -funsigned-bitfields
    -fshort-enums

[env:no_redetect_index_polling]
extends = env:adafruit_feather_m4

[env:redetect_index_polling]
extends = env:adafruit_feather_m4
build_flags =
    ${env:adafruit_feather_m4.build_flags}
    -DRE_DETECT=1

[env:no_redetect_write_polling]
extends = env:adafruit_feather_m4
build_flags =
    ${env:adafruit_feather_m4.build_flags}
    -DUSE_INDEX_POLLING=0

[env:redetect_write_polling]
extends = env:adafruit_feather_m4
build_flags =
    ${env:adafruit_feather_m4.build_flags}
    -DRE_DETECT=1
    -DUSE_INDEX_POLLING=0

[env:no_redetect_write_polling_inverse]
extends = env:redetect_write_polling
build_flags =
    ${env:redetect_write_polling.build_flags}
    -DWRITE_FLAG=1

[env:redetect_write_polling_inverse]
extends = env:redetect_write_polling
build_flags =
    ${env:redetect_write_polling.build_flags}
    -DWRITE_FLAG=1